apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "default-deny"
spec:
  description: "Empty ingress and egress policy to enforce default-deny on all endpoints"
  endpointSelector:
    {}
  ingress:
  - {}
  egress:
  - {}