apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "argocd"
spec:
  description: "Argo CD policy: ingress from Traefik, egress to all K3s API servers/Redis/Internet"
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: argocd
      app.kubernetes.io/part-of: argocd
  ingress:
    # Allow from Traefik
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: traefik
            k8s:io.kubernetes.pod.namespace: infrastructure
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # Allow intercommunication between Argo CD pods
    - fromEndpoints:
        - matchLabels:
          app.kubernetes.io/part-of: argocd
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
            - port: "8081"
              protocol: TCP
  egress:
    # Allow to kube-apiserver
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
    # Allow intercommunication between Argo CD pods
    - toEndpoints:
        - matchLabels:
          app.kubernetes.io/part-of: argocd
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
        - ports:
            - port: "8081"
              protocol: TCP
    # Allow outgoing HTTPS to host and world (internet)
    - toEntities: [host]
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEntities: [world]
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
