apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  namespace: infrastructure
  name: "cert-manager-policy"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  ingress:
  - fromEntities:
      - host
    toPorts:
    - ports:
      - port: "9403"
        protocol: TCP
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
      - ports:
        - port: "6443"
          protocol: TCP
  - toEntities:
    - world
    toPorts:
      - ports:
        - port: "443"
          protocol: TCP
        - port: "53"
          protocol: UDP