apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: hubble-ui
spec:
  description: "Allow Traefik ingress to Hubble UI and required egress"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: hubble-ui
      k8s:io.kubernetes.pod.namespace: kube-system
  ingress:
    # Allow from Traefik
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: traefik
            k8s:io.kubernetes.pod.namespace: infrastructure
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP
  egress:
    # Allow to hubble-relay
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: hubble-relay
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "4245"
              protocol: TCP
            - port: "80"
              protocol: TCP
    # Allow to kube-apiserver
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
