config:
  argocd:
    serverAddress: ${argocd_server_address}
    insecure: true
    tokenSecretName: argocd-image-updater-secret

  registries:
    - name: Harbor
      api_url: ${harbor_api_url}
      defaultns: library
      credentials: ${harbor_credential}
