apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-website-backend
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ark-website-backend
  template:
    metadata:
      labels:
        app: ark-website-backend
    spec:
      containers:
        - name: ark-website-backend
          image: ${image}
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: ark-website-backend-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ark-website-backend-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ark-website-backend-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: ark-website-backend-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: ark-website-backend-secret
                  key: POSTGRES_PORT
            - name: ARK_BACKEND_API
              valueFrom:
                secretKeyRef:
                  name: ark-website-backend-secret
                  key: ARK_BACKEND_API
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
