apiVersion: batch/v1
kind: CronJob
metadata:
  name: ark-scraper
  namespace: ${namespace}
  labels:
    app: ark-scraper
  annotations:
    argocd-image-updater.argoproj.io/image-list: ark-scraper=harbor.schwitzd.me/library/ark-scraper
    argocd-image-updater.argoproj.io/update-strategy: name
spec:
  schedule: "8 8 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1 
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 259200  # 72 hours
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: ark-scraper
        spec:
          restartPolicy: Never
          containers:
            - name: ark-scraper
              image: ${image}
              imagePullPolicy: IfNotPresent
              env:
                - name: TO_EMAILS
                  valueFrom:
                    secretKeyRef:
                      name: ark-scraper-secret
                      key: TO_EMAILS
                - name: MAILER_API_URL
                  valueFrom:
                    secretKeyRef:
                      name: ark-scraper-secret
                      key: MAILER_API_URL
                - name: ARK_TRADE_FILE_URL
                  value: ${ARK_TRADE_FILE_URL}
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: ark-scraper-secret
                      key: POSTGRES_DB
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: ark-scraper-secret
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ark-scraper-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ark-scraper-secret
                      key: POSTGRES_HOST
                - name: POSTGRES_PORT
                  valueFrom:
                    secretKeyRef:
                      name: ark-scraper-secret
                      key: POSTGRES_PORT
              resources:
                requests:
                  cpu: "50m"
                  memory: "128Mi"
                limits:
                  cpu: "150m"
                  memory: "256Mi"
