kubeProxyReplacement: true

l2announcements:
  enabled: true

ipv6:
  enabled: true
ipv6NativeRoutingCIDR: ${ipv6_native_routing_cidr}

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - ${cluster_ipv4_cidr}
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv6PodCIDRList:
      - ${cluster_ipv6_cidr}
    clusterPoolIPv6MaskSize: 120

k8s:
  requireIPv4PodCIDR: false
  requireIPv6PodCIDR: false

k8sServiceHost: ${k8s_service_host}
k8sServicePort: ${k8s_service_port}

externalIPs:
  enabled: true

nodePort:
  enabled: true

bgpControlPlane:
  enabled: false