---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
spec:
  blocks:
    - start: "192.168.14.50"
      stop: "192.168.14.54"
    - start: "fd22:2025:6a6a:42::50"
      stop: "fd22:2025:6a6a:42::54"
