service:
  type: ClusterIP
  port: 80

persistentVolume:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  storageClass: local-path

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    cert-manager.io/cluster-issuer: "le-clusterissuer"
  hosts:
    - host: pgadmin.schwitzd.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-pgadmin-ingress
      hosts:
        - pgadmin.schwitzd.me

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"
