apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-tls
  namespace: database
spec:
  secretName: redis-tls
  issuerRef:
    name: le-clusterissuer
    kind: ClusterIssuer
  commonName: redis.schwitzd.me
  dnsNames:
    - redis.schwitzd.me
