architecture: ${architecture}
commonLabels:
  storage: longhorn

global:
  defaultStorageClass: ${storage_class}

master:
  persistence:
    enabled: true
    size: ${pvc_size}

auth:
  enabled: true
  existingSecret: ${redis_secret}
