service:
  enabled: true
  type: LoadBalancer
  externalIPs:
    - ${traefik_ipv6}
    - ${traefik_ipv4}
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv6
    - IPv4

providers:
  kubernetesGateway:
    enabled: true
    experimentalChannel: false
  kubernetesIngress:
    enabled: false

gatewayClass:
  enabled: true
gateway:
  enabled: false

ports:
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443