---
- name: Sheep SSH key provision
  hosts: localhost
  gather_facts: true

  roles:
    - role: schwitzd.collection.ssh_keygen
      vars:
        ssh_keygen_user: k3s
        ssh_keygen_server: sheep.schwitzd.me
        ssh_keygen_name: sheep.schwitzd.me_ed25519
